# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"Tuple2": "00_fastai_core.ipynb",
         "find_bs2": "00_fastai_core.ipynb",
         "old_find_bs": "00_fastai_core.ipynb",
         "fastai2.torch_core.find_bs": "00_fastai_core.ipynb",
         "detect_batch_to_samples": "03_data.load.ipynb",
         "DetectDataLoader": "03_data.load.ipynb",
         "Annotation": "04_data.core.ipynb",
         "encodes": "04_data.core.ipynb",
         "area": "04_data.core.ipynb",
         "from_mask": "04_data.core.ipynb",
         "PILMaskBinary": "04_data.core.ipynb",
         "TensorMaskBinary": "04_data.core.ipynb",
         "RCNNCallback": "06_callback.ipynb",
         "rcnn_splitter": "08_learner.ipynb",
         "mock_loss": "08_learner.ipynb",
         "mask_rcnn_learner": "08_learner.ipynb"}

modules = ["fastai_core.py",
           "data/load.py",
           "data/core.py",
           "callback.py",
           "learner.py"]

doc_url = "https://lgvaz.github.io/mantisshrimp/"

git_url = "https://github.com/lgvaz/mantisshrimp/tree/master/"

def custom_doc_links(name): return None
