# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"Bucket": "03_data.load.ipynb",
         "old_do_call": "03_data.load.ipynb",
         "detect_batch_to_samples": "03_data.load.ipynb",
         "DetectDataLoader": "03_data.load.ipynb",
         "to_concat2": "03_data.load.ipynb",
         "old_to_concat": "03_data.load.ipynb",
         "fastai2.torch_core.to_concat": "03_data.load.ipynb",
         "nested_reorder2": "03_data.load.ipynb",
         "fastai2.torch_core.nested_reorder": "03_data.load.ipynb",
         "Annotation": "04_data.core.ipynb",
         "encodes": "04_data.core.ipynb",
         "area": "04_data.core.ipynb",
         "from_mask": "04_data.core.ipynb",
         "PILMaskBinary": "04_data.core.ipynb",
         "TensorMaskBinary": "04_data.core.ipynb",
         "GatherPredsCallback.all_tensors": "04_data.core.ipynb",
         "RCNNCallback": "06_callback.ipynb",
         "rcnn_splitter": "08_learner.ipynb",
         "mock_loss": "08_learner.ipynb",
         "mask_rcnn_learner": "08_learner.ipynb"}

modules = ["data/load.py",
           "data/core.py",
           "callback.py",
           "learner.py"]

doc_url = "https://lgvaz.github.io/mantisshrimp/"

git_url = "https://github.com/lgvaz/mantisshrimp/tree/master/"

def custom_doc_links(name): return None
