# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/00_fastai_core.ipynb (unless otherwise specified).

__all__ = ['Tuple2', 'find_bs2', 'old_find_bs']

# Cell
import fastai2.torch_core
from fastcore.all import *

# Cell
class Tuple2(Tuple):
    def __getitem__(self, i):
        res = super().__getitem__(i)
        if isinstance(res, tuple): res = type(self)(res)
        return res

# Cell
old_find_bs = fastai2.torch_core.find_bs
def find_bs2(b):
    # Quick patch because I think it's more dangerous to modify item_find
    if isinstance(b, Tuple2): return len(b)
    return old_find_bs(b)
fastai2.torch_core.find_bs = find_bs2